
services:
  php:
    image: php:8.1.18-fpm-bullseye
    build: ./docker/php
    volumes:
      - './:/app'
    working_dir: /app

  nginx:
    image: nginx:stable-bullseye
    ports:
      - "80:80"
    volumes:
      - './:/app'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
