
services:
  php:
    image: php:8.1.18-fpm-bullseye
    build: ./docker/php
    working_dir: /app
    volumes:
      - './:/app'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=debug-server

  nginx:
    image: nginx:stable-bullseye
    ports:
      - "80:80"
    volumes:
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - './:/app'
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - './docker/mariadb/data:/var/lib/mysql'
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mvc