<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<?php
echo $this->header;
?>
<h2>Добавьте вашу новость:</h2>
<form method="post" action="/post">
    Заголовок: <input type="text" name="title" required="required"><br><br>
    Текст статьи: <textarea name="text" required="required"></textarea><br><br>
    Автор: <input type="text" name="author" required="required"><br><br>
    <input type="submit" value="Отправить">
</form>
</body>
</html>