<!doctype html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Not File</title>
</head>
<body>
<?= $this->header; ?>
<h1>Упс!</h1>
<h2>Кажется, такой страницы не существует</h2>
</body>
</html>