<main class="container">
    <div class="row">
        <div class="d-flex align-items-center flex-column my-5">
            <h1>
                Авторизация
            </h1>
            <?php
            if ($this->keyStatus === 'success') {
                echo '<div class="text-info">Вы успешно авторизованы</div>';
            } else {
                if ($this->keyStatus === 'notFoundUser') {
                    echo '<div  class="text-danger">Пользователь не найден</div>';
                } elseif ($this->keyStatus === 'wrongData') {
                    echo '<div  class="text-danger">Неверно введен пароль</div>';
                }
                echo <<< _END
            <div>
                <form method="post" name="authorization" action="/?controller=authorization&action=authorize">
                    <input class="form-control my-2" type="text" name="user-name" required placeholder="Type Username">
                    <input class="form-control my-2" id="password" type="password" name="user-password" required
                           placeholder="Type password" minlength="6">
                    <input type="submit" class="btn btn-primary my-2" value="Авторизоваться">
                </form>

            </div>
            _END;
            }

            ?>
        </div>

    </div>
</main>