<div class="wrapper">
    <div class="container-fluid fw-bold header">
        <div class="container">
            <div class="row py-3">

                <div class="col-sm-4">
                    <div class="row">
                        <div class="d-flex justify-content-around">
                            <a class="navbar-brand" href="#">BigSportNews</a>
                            <div>
                                <a class="nav-link" aria-current="page"
                                   href=<?= "{$this->domain}/?controller=index&action=renderDefault" ?>>Home</a>
                            </div>
                            <div>
                                <a class="nav-link"
                                   href='<?= "{$this->domain}/?controller=post&action=renderDefault" ?>'>Add
                                    news</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 d-flex justify-content-center">
                    <div class="btn-group me-2">
                        <div class="dropdown">
                            <button class="btn btn-sm dropdown-toggle fw-bold" type="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                Admin Panel
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item"
                                       href="<?= "{$this->domain}/?controller=posts&action=renderDefault" ?>">Posts</a>
                                </li>
                                <li><a class="dropdown-item"
                                       href="<?= "{$this->domain}/?controller=categories&action=renderDefault" ?>">Categories</a>
                                </li>
                                <li><a class="dropdown-item"
                                       href="<?= "{$this->domain}/?controller=users&action=renderDefault" ?>">Users</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 d-flex justify-content-end">
                    <div class="btn-group me-2">
                        <?php if (!$this->userName) { ?>
                            <div class="dropdown">
                                <button class="btn btn dropdown-toggle fw-bold" type="button"
                                        data-bs-toggle="dropdown" aria-expanded="false">
                                    Account
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="/?controller=authorization&action=renderDefault">Sign
                                            in</a></li>
                                    <li><a class="dropdown-item" href="/?controller=registration&action=renderDefault">Sign
                                            up</a></li>
                                </ul>
                            </div>
                        <?php } else { ?>
                            <div>
                                <div><?= $this->userName ?></div>
                                <a href='/?controller=authorization&action=logout'>Log out</a></div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>




