<main>
<?php
if (!$this->posts) {
    echo "<p>Новостей пока нету.</p>";
} else {
    foreach ($this->posts as $post) {
        echo "<article>";
        echo "<h2>" . htmlspecialchars($post->getTitle()) . "</h2>";
        echo "<div>" . htmlspecialchars($post->getText()) . "</div>";
        echo "<h5>Категория: " . htmlspecialchars($post->getCategory()) . "</h5>";
        echo "<h5>Автор: " . htmlspecialchars($post->getAuthor()) . "</h5>";
        echo "<h5>Дата: " . htmlspecialchars($post->getDate()) . "</h5>";
        echo "</article>";
        echo <<<_END
            <form action='' method='post'>
             <input type="hidden" name="delete" value="yes">
            <input type="hidden" name="id" value="{$post->getId()}">
            <input type="submit" value="Удалить новость">
            </form>
            <hr>
           _END;
    }
}
?>
</main>


