<main class="container">
    <div class="row my-3">
        <?php
        if (!$this->posts) {
            echo "<p>Новостей пока нету.</p>";
        } else {
            foreach ($this->posts as $post) {
                echo "<div class='card center-block p-3 my-2'>";
                echo "<div class='card-body'>";
                echo "<h5 class='card-title text-center'>" . $post->getTitle() . "</h5>";
                echo "<div class='card-text'>" . $post->getText() . "</div>";
                echo "<ul class='list group list-group-flush mt-3 h6'>";
                echo "<li class='list-group-item'><b>Категория: </b><i>" . htmlspecialchars($post->getCategory()->getName()) . "</i></li>";
                echo "<li class='list-group-item'><b>Автор: </b><i>" . htmlspecialchars($post->getAuthor()->getName()) . "</i></li>";
                echo "<li class='list-group-item'><b>Дата: </b><i>" . htmlspecialchars($post->getDate()) . "</i></li>";
                echo "</ul>";
                echo "</div></div>";
            }
        }
        ?>
    </div>
    <div class="row my-3 d-flex">
        <div class="d-flex">
            <p>Страница: </p>
            <?php
            for ($i = $this->paginatorPages['first']; $i <= $this->paginatorPages['last']; $i++) {
                if ($i === $this->pageNumber) {
                    echo "<span class='mx-2'>$i</span>";
                } else {
                    echo "<a class='link-primary mx-2 paginator-href' href='{$this->domain}/?controller=index&action=render&page=$i'>$i</a>";
                }
            }
            ?>
        </div>
    </div>
</main>


