<main class="container">
    <div class="row gy-3">
        <?php if (!$this->posts) { ?>
            <p>Новостей пока нету.</p>
        <?php } else {
            foreach ($this->posts as $post) {
                ?>
                <div class='card center-block p-3'>
                    <div class='card-body'>
                        <h5 class='card-title'><?= htmlspecialchars($post->getTitle()) ?></h5>
                        <div class='card-text'><?= htmlspecialchars($post->getText()) ?></div>
                        <ul class='list group list-group-flush'>
                            <li class='list-group-item'>
                                Категория: <?= htmlspecialchars($post->getCategory()->getName()) ?></li>
                            <li class='list-group-item'>
                                Автор: <?= htmlspecialchars($post->getAuthor()->getName()) ?></li>
                            <li class='list-group-item'>Дата: <?= htmlspecialchars($post->getDate()) ?> </li>
                        </ul>
                        <form action='/?controller=posts&action=deletepost' method='post'>
                            <input type='hidden' name='id' value='<?= $post->getId() ?>'>
                            <input type='hidden' name='title' value='<?= $post->getTitle() ?>'>
                            <input type='hidden' name='text' value='<?= htmlspecialchars($post->getText()) ?>'>
                            <input type='hidden' name='authorId' value='<?= $post->getAuthor()->getId() ?>'>
                            <input type='hidden' name='authorName' value='<?= $post->getAuthor()->getName() ?>'>
                            <input type='hidden' name='categoryId' value='<?= $post->getCategory()->getId() ?>'>
                            <input type='hidden' name='categoryName' value='<?= $post->getCategory()->getName() ?>'>
                            <input class='btn btn-danger mx-1' type='submit' value='Удалить новость'>
                            <div class='btn btn-primary' onclick='toggleEditModal(this)'> Редактировать новость</div>
                        </form>
                    </div>
                </div>
                <?php
            }
        }
        ?>
    </div>
    <div class="row my-3 d-flex">
        <div class="d-flex">
            <p>Страница: </p>
            <?php
            for ($i = $this->paginatorPages['first']; $i <= $this->paginatorPages['last']; $i++) {
                if ($i === $this->pageNumber) {
                    ?>
                    <span class='mx-2'><?= $i ?></span>

                <?php } else { ?>
                    <a class='link-primary mx-2 paginator-href'
                       href='<?= $this->domain ?>/?controller=posts&action=renderDefault&page=<?= $i ?>'><?= $i ?></a>
                <?php }
            }
            ?>
        </div>
    </div>
    <div id="edit-modal" class="modal-wrapper hidden">
        <div class="form-wrapper">
            <form action='/?controller=posts&action=updatePost' method='post'>
                <input type="hidden" id="input-id-edit" name="id" value="">
                <label class="form-label"> Заголовок:</label><br>
                <input type="text" class="form-control" name="title" id="input-title-edit" required="required"><br>
                <label class="form-label"> Текст статьи:</label><br>
                <textarea class="form-control" id="input-text-edit" name="text" required="required" rows="5"></textarea><br>
                <label class="form-label"> Автор:</label>
                <select name="author" id="input-author-edit" size="1" required class="form-select">
                    <option value="" selected disabled>Выберите автора</option>
                    <?php
                    foreach ($this->users as $user) {
                        echo "<option value='{$user->getId()}'>{$user->getName()}</option>>";
                    }
                    ?>
                </select><br>
                <label class="form-label"> Категория:</label>
                <select class="form-select" id="input-category-edit" name="category" size="1" required>
                    <option selected disabled value="">Выберите категорию</option>
                    <?php
                    foreach ($this->categories as $category) {
                        ?>
                        <option value='<?= $category->getId() ?>'><?= $category->getName() ?></option>>";
                    <?php } ?>
                    <input class="btn btn-primary my-4" type="submit" value="Редактировать пост">
                    <div class="btn btn-secondary" onclick="toggleEditModal(null)">Отменить</div>
            </form>
        </div>
    </div>

</main>

<script src="/public/scripts/posts/posts.js"></script>


