<main class="container d-flex align-items-center justify-content-center">
    <div class="center-block">
        <div class="spinner-border" role="status">
            <span class="visually-hidden">Загрузка...</span>
        </div>
        <p>Пользователь успешно создан. Вы будете автоматически перенаправлены на главную страницу</p>
    </div>
    <script src="/public/scripts/common/redirect.js">
    </script>
</main>