<main class="container">
    <div class="row">
        <div class="d-flex align-items-center flex-column my-5">
            <h1>
                Регистрация
            </h1>
            <?php
            echo <<< _END
            <div>
            <form method="post" action="/?controller=registration&action=register">
            <label for="text" class="form-label mt-5">Введите имя нового пользователя</label>
            <input class="form-control" type="text" name="user-name" required>
            <input type="submit" class="btn btn-primary my-2" value="Зарегистрировать">
            </form>
            _END;

            ?>
        </div>
        </div>

    </div>
</main>
