<main class="container">
    <div class="row gy-3 my-3">
        <?php if (!$this->users) { ?>
            <p>Пользователей нету.</p>
            <?php
        } else {
            foreach ($this->users as $user) {
                ?>
                <div class='card center-block p-3'>
                    <div class='card-body'>
                        <div class='card-text'> ID: <?= htmlspecialchars($user->getId()) ?></div>
                        <div class='card-text'>Name: <?= htmlspecialchars($user->getName()) ?></div>
                        <form action='/?controller=users&action=delete' method='post'>
                            <input type="hidden" name="delete" value="yes">
                            <input type="hidden" name="id" value="<?= $user->getId() ?>">
                            <input type="hidden" name="name" value="<?= $user->getName() ?>">
                            <input class="btn btn-danger" type="submit" value="Удалить пользователя">
                            <div class='btn btn-primary' onclick='toggleEditModal(this)'>Редактировать</div>
                        </form>
                    </div>
                </div>
            <?php } ?>
            <div id="edit-modal" class="modal-wrapper hidden">
                <div class="form-wrapper">
                    <form action='/?controller=users&action=updateUser' method='post'>
                        <input type="input" id="input-name-edit" name="name" value="">
                        <input type="hidden" name="edit" value="yes">
                        <input type="hidden" id="input-id-edit" name="id" value="">
                        <input class="btn btn-primary" type="submit" value="Редактировать пользователя">
                        <div class="btn btn-primary" onclick="toggleEditModal(null, null)">Отменить</div>
                    </form>
                </div>
            </div>
        <?php } ?>
    </div>
</main>
<script src="/public/scripts/users/users.js"></script>